<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;

/**
 * Class UserSeeder
 *
 * This class is responsible for seeding the User table in the database.
 * It extends Laravel's Seeder class.
 */
class UserSeeder extends Seeder
{

    /**
     * Run the database seeds.
     *
     * This method creates a single user with predefined values for testing purposes.
     * It also creates 10 additional users with random data generated by the User factory.
     *
     * The 'password' attribute is hashed using Laravel's bcrypt function for security.
     */

    public function run(): void
    {
    \App\Models\User::factory()->create([
            'name' => fake()->name(),
            'email' => fake()->email(),
            'password' => bcrypt(123)
        ]);
        // Create 10 random users
        User::factory()->count(10)->create();
    }
}
